# Project info
site_name: The Automation Hub
site_description: 'Documentation, guides and articles on creating, developing and implementing automated betting strategies, using data analysis to inform betting models and how to interact with the Betfair API.'
site_author: 'Betfair Data Scientists'
site_url: 'https://betfair-datascientists.github.io'
docs_dir: 'src'
site_dir: 'docs'

# Navigation
nav:
    - Home: index.md  
    - API:
        - API resources: api/apiResources.md
        - How to access the Betfair API: api/apiappkey.md
        - Tutorials:
            - API tutorials in R: api/apiRtutorial.md
            - API tutorial in Python: api/apiPythontutorial.md
        - Golden rules of automation: api/GoldenRulesofAutomation.md
    - Historic Data: 
        - Pricing Data Sources: historicData/dataSources.md
        - Tutorials:
            - JSON to CSV in Python: historicData/jsonToCsvTutorial.md
            - Back testing ratings in Python: historicData/backtestingRatingsTutorial.md
            - Automated betting angles in Python: historicData/automatedBettingAnglesTutorial.ipynb
            - Do \#theyknow? Analysing Betfair market formation & market movements: historicData\analysingAndPredictingMarketMovements.ipynb
            - Wisdom of the crowd? Analysing & understanding BSP: historicData\analysingAndPredictingBSP.ipynb
            
        - Historic Data site:
            - Downloading from the Historic Data site: historicData/usingHistoricDataSite.md
    - Modelling:
        - Intro to modelling: modelling/howToModel.md
        - Racing:
            - Greyhound form FastTrack API: modelling/fasttrackTutorial.ipynb
            - Greyhound modelling in Python: modelling/greyhoundModellingPython.ipynb
        - Soccer:
            - Elo soccer tutorial in R: modelling/soccerEloTutorialR.md
            - Soccer modelling tutorial in Python: modelling/soccerModellingTutorialPython.md
            - Soccer modelling tutorial in R: modelling/soccerModellingTutorialR.md
            - EPL ML walk through in Python: modelling/EPLmlPython.md
        - AFL:
            - AFL modelling walk through in Python: modelling/AFLmodellingPython.md
            - Modelling the Brownlow Medal in Python: modelling/brownlowModelTutorial.md
        - Tennis:
            - How to model the Australian Open: modelling/howToModelTheAusOpen.md
            - Aus Open R Tutorial: modelling/AusOpenRTutorial.md
            - Aus Open Python Tutorial: modelling/AusOpenPythonTutorial.md
    - Auto Tools: 
        - Tools Overview: autoTools/overview.md           
        - Bet Angel: 
            - Overview: autoTools/betAngel/betAngel.md
            - Beginner's guide: autoTools/betAngelbeginners.md
            - Intermediate guide: autoTools/betAngelintermediate.md
            - Advanced guide: autoTools/betAngeladvanced.md
            - Ratings auto: autoTools/betAngelRatingsAutomation.md
            - Market fav auto: autoTools/betAngelMarketFavouriteAutomation.md
            - Tipping auto: autoTools/betAngelTippingAutomation.md
            - Simultaneous markets: autoTools/betAngelSimultaneousMarkets.md
            - Kelly criterion staking: autoTools/betAngelKellyStake.md
        - Gruss Betting Assistant:
            - Overview: autoTools/Gruss/Gruss.md
            - Setup basic market view and one click betting: autoTools/GrussSettingupbasicmarketview.md
            - Ratings auto: autoTools/grussRatingsAutomation.md
            - Market fav auto: autoTools/grussMarketFavouriteAutomation.md
            - Simultaneous markets: autoTools/grusslSimultaneousMarkets.md
            - Kelly criterion staking: autoTools/grussKellyStake.md
        - Cymatic Trader: 
            - Overview: autoTools/CymaticTrader/CymaticTrader.md
            - Ratings auto: autoTools/cymaticTraderRatingsAutomation.md      
        - Geeks Toy:
            - Installation and setup: autoTools/GeeksToyinstallationandsetup.md
            - Setup basic market view and one click betting: autoTools/GeeksToybasicmarketviewstakingandoneclickbetting.md
            - Optimising refresh settings: autoTools/geeksToyRefreshSettings.md

# Theme settings
theme:
    name: material
    custom_dir: 'theme'
    favicon: 'img/BetfairFavicon.ico'
    logo: 'img/logo.svg'
    language: 'en'
    palette:
        -   scheme: betfair
            primary: amber
            accent: orange
            media: "(prefers-color-scheme: light)" 
            toggle:
                icon: material/weather-night
                name: Switch to dark mode
        -   scheme: slate
            primary: amber
            accent: orange
            media: "(prefers-color-scheme: dark)" 
            toggle:
                icon: material/weather-sunny
                name: Switch to light mode
    font:
        text: 'Roboto'
        code: 'Roboto Mono' 
    features:
        - toc.integrate
        - navigation.instant
        - navigation.tabs
        - navigation.top
        - navigation.expand
        - navigation.sections
        - search.suggest
        - search.highlight
        - search.share

# Extensions
markdown_extensions:
    - admonition
    - meta
    - md_in_html
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.inlinehilite
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.superfences

# plugins
plugins:
   - search
   - mknotebooks

# Google Analytics
google_analytics:
    - 'UA-125973915-1'
    - 'auto'

extra:
    rg_footer: 'Think! About your choices. Stay in control. Leave before you lose it. Gamble responsibly.'
    generator: false
    # Social Media links (footer)
    social:
        - icon: fontawesome/brands/twitter
          link: https://twitter.com/Betfair_Aus
        - icon: fontawesome/brands/linkedin
          link: https://linkedin.com/company/betfair-australia
        - icon: fontawesome/brands/facebook
          link: https://facebook.com/betfairaustralia
        - icon: fontawesome/brands/youtube
          link: https://youtube.com/user/betfairaus
        - icon: fontawesome/brands/github
          link: https://github.com/betfair-datascientists

# betfair custom theme css file
extra_css:
    - assets/stylesheets/betfair.css
